# Generated by Django 2.0.1 on 2018-06-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usrid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
