# Generated by Django 2.0.1 on 2018-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_data_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datapath',
            field=models.CharField(max_length=300),
        ),
    ]
