# Generated by Django 2.0.1 on 2018-07-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180702_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datatype',
            field=models.CharField(default='text', max_length=50),
            preserve_default=False,
        ),
    ]
