# Generated by Django 2.0.1 on 2018-08-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_data_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='expid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
