# Generated by Django 2.0.1 on 2018-08-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180820_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='expname',
            field=models.CharField(max_length=200),
        ),
    ]
