# Generated by Django 2.0.1 on 2018-08-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180822_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usrfirstname',
            field=models.CharField(default='first', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='usrlastname',
            field=models.CharField(default='last', max_length=20),
            preserve_default=False,
        ),
    ]
