# Generated by Django 2.0.1 on 2018-08-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20180827_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usrid',
            field=models.AutoField(default=100000, primary_key=True, serialize=False),
        ),
    ]
