# Generated by Django 2.0.1 on 2018-08-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180827_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='usrid',
        ),
        migrations.AddField(
            model_name='users',
            name='usrname',
            field=models.CharField(default='evelyn', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
