# Generated by Django 2.0.1 on 2018-08-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_experiment_exptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usremail',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
