# Generated by Django 2.0.1 on 2018-08-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20180828_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='refer_no',
        ),
    ]
