# Generated by Django 2.0.1 on 2018-09-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_remove_data_refer_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datadescription',
            field=models.CharField(default="text file that describe the participant's features", max_length=400),
            preserve_default=False,
        ),
    ]
